<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<h1>Intro</h1>
<section>
    <p>
        This site is built exclusively using the code that is found in the dependencies section below and all forms are built exclusively using the
        code found in this projects github repo. This project is not affiliated with or endorsed by either of the projects and is developed solely
        by Webinertia and contributors. Our primary goals for this project is outlined below and as they evolve you will be able to find them in
        our github repo under the projects tab.
    </p>
    <h4>Laminas Form:</h4>
    <p>
        Provide not only the view helpers for rendering bootstrapped elements, but also providing means for which
        to integrate 100% bootstrap functionaly in regards to form layout and validation while coding the form classes themselves. We hope to quickly
        have this integration working even when building forms strictly from configuration or annotations currently scheduled for v1.3.0 - v1.5.0.
    </p>
    <h4>Laminas View:</h4>
    <p>
        Our goal is to provide bootstrapped versions of all of the Laminas View Helpers for which it makes sense and will be useful to have a
        version that can be configured to render with Bootstrap styling.
    </p>
</section>
<section>
    <h3>Dependencies &amp; Resources</h3>
    <div class="row g4">
        <div class="col">
            <div class="card">
                <h6 class="card-header">Dependencies</h6>
                <div class="card-body">
                    <div class="list-group">
                        <a href="https://docs.laminas.dev/laminas-form/v3/quick-start/" class="list-group-item" target="_blank">Laminas Form</a>
                        <a href="https://docs.laminas.dev/laminas-navigation/quick-start/" class="list-group-item" target="_blank">Laminas Navigation</a>
                        <a href="https://docs.laminas.dev/laminas-view/quick-start/" class="list-group-item" target="_blank">Laminas View</a>
                        <a href="https://getbootstrap.com/docs/5.3/getting-started/introduction/" class="list-group-item" target="_blank">Bootstrap 5.3</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <h6 class="card-header">Follow Development</h6>
                <div class="card-body">
                    <p>
                        If you are interested in following the development, you can check our
                        <a href="https://github.com/webinertia/bootstrap/discussions">Project discussions</a>,
                        and <a href="https://github.com/webinertia/bootstrap/issues">Issue tracker</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <h6 class="card-header">Help &amp; Support</h6>
                <div class="card-body">
                    <p>
                        If you need help or support we have a
                        <a href="https://github.com/webinertia/bootstrap/wiki">wiki</a> or
                        <a href="https://webinertia-chat.slack.com">chat</a>.
                        We'd love to hear from you!
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

